#pragma once

//#include <juce_core.h>
//#include <juce_data_structures.h>
//#include <juce_gui_basics.h>
//#include <juce_graphics.h>
//#include <juce_events.h>
#include <algorithm>
#include <chrono>
#include <cstdlib>
#include <ctime>
#include <filesystem>
#include <functional>
#include <iomanip>
#include <iostream>
#include <libproc.h>
#include <map>
#include <memory>
#include <optional>
#include <regex>
#include <sstream>
#include <stdexcept>
#include <string>
#include <sys/sysctl.h>
#include <unistd.h>
#include <unordered_map>
#include <unordered_set>
#include <vector>
